#!/usr/bin/env python3
"""WAF Fingerprinting & Bypass Suggestions
Detects Cloudflare, Akamai, AWS WAF, Incapsula, Sucuri, ModSecurity, etc.
and suggests bypass techniques per WAF.
"""

import argparse
import requests
import urllib3
urllib3.disable_warnings()

WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": {"server": "cloudflare", "cf-ray": None},
        "cookies": ["__cflb", "__cfuid", "cf_clearance"],
        "body_patterns": ["cf-browser-verification", "attention required", "cloudflare-nginx", "cf_chl_opt"],
        "status_codes": [403, 503],
        "bypass": [
            "Find origin IP: crt.sh + DNS history + email headers",
            "Direct IP + Host header bypass",
            "Use Cloudflare Workers as proxy",
            "Chunked transfer encoding bypass",
            "Unicode/encoding bypass in path",
            "Try HTTP/2 with h2c upgrade",
        ]
    },
    "Akamai": {
        "headers": {"x-akamai-transformed": None, "server": "akamaighost"},
        "cookies": ["akamai_"],
        "body_patterns": ["access denied", "the requested url was rejected"],
        "status_codes": [403],
        "bypass": [
            "Origin IP discovery via subdomain enumeration",
            "HTTP parameter pollution",
            "Null byte in path: /%00/",
            "Unicode normalization bypass",
        ]
    },
    "AWS WAF": {
        "headers": {"x-amzn-requestid": None, "x-amz-cf-id": None, "server": "amazons3"},
        "cookies": ["aws-waf-token"],
        "body_patterns": ["403 forbidden", "aws waf"],
        "status_codes": [403],
        "bypass": [
            "Try different AWS regions (WAF rules may differ)",
            "API Gateway direct endpoint",
            "CloudFront origin bypass",
            "HTTP/2 request smuggling",
        ]
    },
    "Incapsula/Imperva": {
        "headers": {"x-iinfo": None, "server": "incapsula"},
        "cookies": ["visid_incap_", "incap_ses_", "nlbi_"],
        "body_patterns": ["incapsula incident id", "access to this site is blocked"],
        "status_codes": [403, 406],
        "bypass": [
            "Origin IP via DNS history",
            "X-Forwarded-For spoofing",
            "Cookie manipulation",
            "WebSocket upgrade bypass",
        ]
    },
    "Sucuri": {
        "headers": {"server": "sucuri/cloudproxy", "x-sucuri-id": None},
        "cookies": ["sucuri_cloudproxy"],
        "body_patterns": ["access denied", "sucuri website firewall", "blocked by sucuri"],
        "status_codes": [403],
        "bypass": [
            "Origin IP discovery",
            "DNS history lookup",
            "Email header analysis for origin IP",
        ]
    },
    "ModSecurity": {
        "headers": {"server": "mod_security", "x-mod-security": None},
        "cookies": [],
        "body_patterns": ["mod_security", "modsecurity", "this error was generated by mod_security", "not acceptable"],
        "status_codes": [403, 406, 501],
        "bypass": [
            "Chunked encoding bypass",
            "Unicode/UTF-8 encoding",
            "Case variation: SeLeCt vs select",
            "Comment injection: SEL/**/ECT",
            "Null byte: %00",
            "Double URL encoding",
            "HTTP parameter pollution",
        ]
    },
    "F5 BIG-IP": {
        "headers": {"server": "bigip", "x-waf": None},
        "cookies": ["BIGipServer", "TS01"],
        "body_patterns": ["the requested url was rejected"],
        "status_codes": [403],
        "bypass": [
            "Cookie manipulation (BIGipServer cookie reveals internal IP)",
            "HTTP request smuggling",
            "Host header manipulation",
        ]
    },
    "FortiWeb": {
        "headers": {"server": "fortiweb"},
        "cookies": [],
        "body_patterns": ["fortiweb", "blocked by fortiguard"],
        "status_codes": [403],
        "bypass": [
            "Unicode bypass",
            "Double encoding",
            "Case variation",
        ]
    },
    "Barracuda": {
        "headers": {"server": "barracuda"},
        "cookies": ["barra_counter_session"],
        "body_patterns": ["barracuda", "web application firewall"],
        "status_codes": [403],
        "bypass": [
            "Chunked encoding",
            "HTTP parameter pollution",
            "Null byte injection",
        ]
    },
    "Wordfence": {
        "headers": {},
        "cookies": [],
        "body_patterns": ["wordfence", "generated by wordfence", "your access to this site has been limited"],
        "status_codes": [403, 503],
        "bypass": [
            "Origin IP discovery (WordPress behind CDN)",
            "XML-RPC endpoint bypass (/xmlrpc.php)",
            "WP-JSON REST API direct access",
            "wp-admin direct access via origin IP",
        ]
    },
}

def detect_waf(url, timeout=10):
    """Detect WAF by sending malicious payloads and analyzing responses."""
    results = []
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}
    
    # Malicious payloads to trigger WAF
    payloads = [
        ("SQLi", "/?id=1' OR '1'='1"),
        ("XSS", "/?q=<script>alert(1)</script>"),
        ("Path Traversal", "/../../../etc/passwd"),
        ("RCE", "/?cmd=;cat /etc/passwd"),
        ("Scanner Detection", "/?id=<scRiPt>"),
    ]
    
    print(f"\033[94m[*]\033[0m Sending baseline request to {url}")
    
    # Get baseline response
    try:
        baseline = requests.get(url, headers=headers, timeout=timeout, verify=False, allow_redirects=False)
        baseline_len = len(baseline.text)
    except Exception as e:
        print(f"\033[91m[-]\033[0m Cannot connect: {e}")
        return []
    
    detected = set()
    
    # Check baseline headers for WAF signatures
    resp_headers = {k.lower(): v for k, v in baseline.headers.items()}
    resp_cookies = [c.name for c in baseline.cookies]
    body_lower = baseline.text.lower()
    
    for waf_name, sig in WAF_SIGNATURES.items():
        # Check headers
        for hkey, hval in sig["headers"].items():
            if hkey in resp_headers:
                if hval is None or hval.lower() in resp_headers[hkey].lower():
                    detected.add(waf_name)
                    results.append({"waf": waf_name, "evidence": f"Header: {hkey}: {resp_headers[hkey]}", "source": "baseline"})
        
        # Check cookies
        for c in sig["cookies"]:
            if any(c.lower() in rc.lower() for rc in resp_cookies):
                detected.add(waf_name)
                results.append({"waf": waf_name, "evidence": f"Cookie: {c}", "source": "baseline"})
        
        # Check body
        for pat in sig["body_patterns"]:
            if pat.lower() in body_lower:
                detected.add(waf_name)
                results.append({"waf": waf_name, "evidence": f"Body pattern: {pat}", "source": "baseline"})
    
    # Send malicious payloads to trigger WAF
    for ptype, payload in payloads:
        try:
            test_url = url.rstrip("/") + payload
            r = requests.get(test_url, headers=headers, timeout=timeout, verify=False, allow_redirects=False)
            
            test_headers = {k.lower(): v for k, v in r.headers.items()}
            test_body = r.text.lower()
            test_cookies = [c.name for c in r.cookies]
            
            # If different from baseline (status code change, body length change)
            is_blocked = (r.status_code != baseline.status_code or 
                         (r.status_code in [403, 406, 503] and abs(len(r.text) - baseline_len) > 100))
            
            if is_blocked:
                for waf_name, sig in WAF_SIGNATURES.items():
                    if waf_name in detected:
                        continue
                    for hkey in sig["headers"]:
                        if hkey in test_headers:
                            detected.add(waf_name)
                            results.append({"waf": waf_name, "evidence": f"Header on {ptype}: {hkey}: {test_headers[hkey]}", "source": "payload"})
                    for pat in sig["body_patterns"]:
                        if pat.lower() in test_body:
                            detected.add(waf_name)
                            results.append({"waf": waf_name, "evidence": f"Body on {ptype}: {pat}", "source": "payload"})
        except:
            continue
    
    # Generic WAF detection
    if not detected:
        if baseline.status_code in [403, 503]:
            results.append({"waf": "Unknown WAF", "evidence": f"Status {baseline.status_code} on baseline", "source": "heuristic"})
        for ptype, payload in payloads:
            try:
                r = requests.get(url.rstrip("/") + payload, headers=headers, timeout=timeout, verify=False, allow_redirects=False)
                if r.status_code in [403, 406, 503] and r.status_code != baseline.status_code:
                    results.append({"waf": "Unknown WAF", "evidence": f"Blocked {ptype} with {r.status_code}", "source": "heuristic"})
                    break
            except:
                continue
    
    return results


def main():
    parser = argparse.ArgumentParser(description="WAF Fingerprinting & Bypass Suggestions")
    parser.add_argument("url", help="Target URL")
    parser.add_argument("--timeout", type=int, default=10)
    args = parser.parse_args()
    
    url = args.url.rstrip("/")
    if not url.startswith("http"):
        url = "https://" + url
    
    print(f"\033[95m[+]\033[0m WAF Detection — {url}")
    print("=" * 60)
    
    results = detect_waf(url, args.timeout)
    
    if not results:
        print("\033[92m[✓]\033[0m No WAF detected (or WAF is transparent)")
        return
    
    # Deduplicate and display
    seen = set()
    for r in results:
        if r["waf"] in seen:
            continue
        seen.add(r["waf"])
        print(f"\n\033[91m[!] WAF: {r['waf']}\033[0m")
        print(f"    Evidence: {r['evidence']}")
        
        # Show bypass suggestions
        for waf_name, sig in WAF_SIGNATURES.items():
            if waf_name == r["waf"]:
                print(f"    \033[93mBypass techniques:\033[0m")
                for i, b in enumerate(sig["bypass"], 1):
                    print(f"      {i}. {b}")
                break
    
    print(f"\n{'=' * 60}")
    print(f"Total WAFs detected: {len(seen)}")
    
    # Output JSON
    import json
    out = {"url": url, "wafs_detected": list(seen), "details": results}
    with open("output/waf_detect.json", "w") as f:
        json.dump(out, f, indent=2)
    print(f"[*] Results saved to output/waf_detect.json")


if __name__ == "__main__":
    main()
